#!/usr/bin/env node
// build.mjs – Concatenates all src/ modules into profiler-standalone.js
//
// Usage:
//   node build.mjs
//   node build.mjs --watch      (rebuild on file changes, requires Node 22+ or a watcher)
//
// Module order matters: each module depends on symbols defined by the modules
// that come before it.

import { readFileSync, writeFileSync, readdirSync, watchFile } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, 'src');
const OUT_FILE = join(__dirname, 'profiler-standalone.js');

function build() {
  // Explicit module order — each module depends on symbols defined by earlier ones
  const MODULE_ORDER = [
    'timing-helper.js',
    'data-store.js',
    'memory-leak-detector.js',
    'workgroup-analyzer.js',
    'shader-analyzer.js',
    'init-logging.js',
    'broadcast.js',
    'utils.js',
    'bandwidth-tracker.js',
    'webgpu-hooks.js',
    'public-api.js',
  ];
  const modules = MODULE_ORDER.map(f => join(SRC_DIR, f));

  const header = `// WebGPU Performance Profiler
// Hooks into WebGPU API to capture GPU timing, pipeline usage, memory allocations,
// and dispatch statistics. Broadcasts profiler data via BroadcastChannel for real-time visualization.
//
// AUTO-GENERATED – do not edit this file directly.
// Edit the source modules in src/ and run: node build.mjs
//   src/timing-helper.js      TimingHelper class (timestamp query management)
//   src/data-store.js         profilerData central store
//   src/memory-leak-detector.js  MemoryLeakDetector class
//   src/workgroup-analyzer.js WorkgroupOccupancyAnalyzer class
//   src/shader-analyzer.js     ShaderComplexityAnalyzer class
//   src/init-logging.js        Analyzer singletons + log/warn/error helpers
//   src/broadcast.js           BroadcastChannel + broadcastData + control messages
//   src/utils.js               normalizeTime, hashString, extractWorkgroupSize, addLog, …
//   src/bandwidth-tracker.js   BandwidthTracker, parseWGSLBindings, texture helpers
//   src/webgpu-hooks.js        hookWebGPU() – intercepts the full WebGPU API
//   src/public-api.js          window.WebSight public API + initialization

`;

  const body = modules
    .map(f => {
      const raw = readFileSync(f, 'utf8');
      const name = f.split('/').pop();
      // Strip ES module import/export syntax before wrapping in IIFE
      const content = raw
        .replace(/^export\s*\{[^}]*\};\s*\n?/gm, '')     // export { a, b };
        .replace(/^import\s[^\n]+\n/gm, '')                // import ... from '...'
        .replace(/^export\s+(async\s+function|function|class|const|let|var)\s/gm, '$1 ');
      return `  // --- ${name} ---\n` +
        content.split('\n').map(l => '  ' + l).join('\n');
    })
    .join('\n\n');

  const output = `${header}(function() {\n  'use strict';\n\n${body}\n})();\n`;

  writeFileSync(OUT_FILE, output, 'utf8');

  const totalLines = output.split('\n').length;
  console.log(`[build] Written ${OUT_FILE} (${totalLines} lines, ${modules.length} modules)`);
}

build();

if (process.argv.includes('--watch')) {
  console.log('[build] Watching src/ for changes…');
  const srcFiles = readdirSync(SRC_DIR)
    .filter(f => f.endsWith('.js'))
    .map(f => join(SRC_DIR, f));

  srcFiles.forEach(f => {
    watchFile(f, { interval: 500 }, () => {
      console.log(`[build] Changed: ${f.split('/').pop()}`);
      build();
    });
  });
}
